### ISSUE TITLE
Create Comprehensive Setup Readme

### ISSUE THREAD

**Issue by koolamusic** [wecodeafrica/backend#13]
Need help in Creating a comprehensive readme on how to setup the python Django project and API

**Comment by mdaizovi** [comment]
Do you mean elaborate on the current readme? Telling the user to pip install, run the server, etc? If so, I'd love to do this, just let me know.

**Comment by koolamusic** [comment]
Yes, a GIF would be a wonderful feature to that as well. 
Thanks

**Comment by mdaizovi** [comment]
I wasn't sure what to make a gif of, all of the commands? I jsut wrote them very explicitly. What do you think? It worked for me to create a local environment:
https://github.com/wecodeafrica/backend/issues/13
