### ISSUE TITLE
Deploy API to Heroku

### ISSUE THREAD

**Issue by koolamusic** [wecodeafrica/backend#26]
Deploy the API to an Heroku Instance

**Comment by koolamusic** [comment]
The Travis Build is not working yet, 
- How do we go about this @Subomi

**Comment by Subomi** [comment]
Looking into It.

**Comment by Subomi** [comment]
All the requirements were bumped up to newer and most likely incompatible versions. I'll suggest we downgrade all back. We can take reference from [My Fork for base](https://github.com/Subomi/backend/blob/e9f309fa96c371f9b6a0fd7a311c32ec4739d62c/requirements/base.txt#L1) and [My Fork for local](https://github.com/Subomi/backend/blob/e9f309fa96c371f9b6a0fd7a311c32ec4739d62c/requirements/local.txt#L1)

**Comment by Subomi** [comment]
Then i need some access to this repo to add some environment variables for travis.

**Comment by koolamusic** [comment]
ok, I will check through it
Access Granted

**Comment by koolamusic** [comment]
check for compatibility, I would like to work with the newer versions

**Comment by Subomi** [comment]
Deployed.

**Comment by koolamusic** [comment]
URL

**Comment by Subomi** [comment]
https://mpa-dev.herokuapp.com/

**Comment by koolamusic** [comment]
ok, Nice 
The is an error page on the default url
Please how do i find documentation

**Comment by Subomi** [comment]
Crap! That version is with the newly merged profiles app. I'd deploy ASAP and update here.

**Comment by koolamusic** [comment]
Alright will be monitoring for changes

**Comment by shapkarin** [comment]
I think you need some kind of decentrilised database and even host. Like to have some nodes and next people can create a new ones. Not sure about any solutions but it's an idea.

**Comment by koolamusic** [comment]
@shapkarin I'd take a look into that

**Comment by mdaizovi** [comment]
Is this app deployed anywhere? I went to the page linked from backend description and got a 404
![Screen Shot 2019-10-19 at 9 05 26 PM](https://user-images.githubusercontent.com/10183580/67150179-625fee80-f2b4-11e9-87d0-cd6e1f80ba5d.png)

**Comment by koolamusic** [comment]
our deploy seems to be broken, could you propose a solution

**Comment by mdaizovi** [comment]
Actually the deployment isn't broken, I just didn't realize there was no `/` page when I posted that. For example I can get to:
`https://mpa-dev.herokuapp.com/auth/register/`
But you're never supposed to deploy with DEBUG=True,  which this is.

**Comment by shapkarin** [comment]
> I think you need some kind of decentrilised database and even host. Like to have some nodes and next people can create a new ones. Not sure about any solutions but it's an idea.

@koolamusic not sure that it can help but you can have a look at https://github.com/tootsuite/mastodon

**Comment by koolamusic** [comment]
I totally buy the idea of a decentralized database right now.
Thinking about this, not sure mastodon is a right fit. 

However, I am open to more options and will start looking out for opportunities in this space. 
A decentralized database will greatly benefit a project of this sort, and happy to check out any recommendations you have. @shapkarin

**Comment by shapkarin** [comment]
@koolamusic maybe even we can start some project that will help any other ones if it's not already exist. 
And on base of that project create missing people backend.

**Comment by shapkarin** [comment]
@koolamusic https://docs.ipfs.io it's no actually a DB but can be used to serve files
